name: CoolPC Parser 自動執行並提交至 getProduct 分支

on:
  schedule:
    - cron: '0 */1 * * *' # 每1小時執行一次 (UTC 時間)
  workflow_dispatch: # 允許手動觸發

jobs:
  run_parser_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: 檢查程式碼並切換到 getProduct 分支
      uses: actions/checkout@v4
      with:
        ref: getProduct # 指定要檢查的分支
        fetch-depth: 0 # 需要完整的歷史記錄才能檢查檔案變動

    - name: 設定 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: 安裝必要的 Python 模組
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt # 如果您的 coolpc_parser.py 檔案需要額外模組，請解除註解此行

    - name: 執行 CoolPC Parser
      run: python3 coolpc_parser.py --download --json product.json
      # 這個指令會將 product.json 產生在專案根目錄。

    - name: 檢查並提交 product.json 變更至 getProduct 分支
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # 添加 product.json
        git add product.json

        # 檢查 product.json 是否有任何檔案變更
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto: 更新 product.json [getProduct branch]" # 更新提交訊息
          git push origin HEAD:getProduct # 推送到 getProduct 分支
        else
          echo "沒有新的變更需要推送到遠端 getProduct 分支。"
        fi
      if: success()
