name: CoolPC Parser 自動執行與提交

on:
  schedule:
    - cron: '0 */1 * * *' # 每3小時執行一次 (UTC 時間)
  workflow_dispatch: # 允許手動觸發

jobs:
  run_parser_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: 檢查程式碼
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 需要完整的歷史記錄才能檢查檔案變動

    - name: 設定 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: 安裝必要的 Python 模組
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 執行 CoolPC Parser
      run: python3 coolpc_parser.py --download --json product.json

    - name: 檢查並提交變更
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # 檢查是否有檔案變更
        git add evaluate.html product.json
        git diff-index --quiet HEAD || git commit -m "Auto: 更新 evaluate.html 和 product.json"
        
        # 如果有新的提交，則推送到遠端倉庫
        git push || echo "沒有新的變更需要推送到遠端。"
